# Generated by Django 4.2 on 2023-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='files/avatar')),
            ],
        ),
        migrations.CreateModel(
            name='DBTest',
            fields=[
                ('TestId', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='files/cover')),
            ],
        ),
    ]
